// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveRuns():Promise<string>;

export function GetFilePath():Promise<string>;

export function ProcessANPFile(arg1:string):Promise<void>;

export function ResetANP():Promise<void>;

export function SaveANPFile():Promise<void>;

export function ShowActiveRuns():Promise<void>;
