// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveRuns() {
  return window['go']['main']['App']['GetActiveRuns']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function ProcessANPFile(arg1) {
  return window['go']['main']['App']['ProcessANPFile'](arg1);
}

export function ResetANP() {
  return window['go']['main']['App']['ResetANP']();
}

export function SaveANPFile() {
  return window['go']['main']['App']['SaveANPFile']();
}

export function ShowActiveRuns() {
  return window['go']['main']['App']['ShowActiveRuns']();
}
